apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: sigo-ms
  labels:
    app: postgres
data:
  POSTGRES_DB: msgestaonormas
  POSTGRES_USER: msgestaonormas
  POSTGRES_HOST: postgres-service
  POSTGRES_PORT: '5432'
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: sigo-ms
  labels:
    app: postgres
data:
  POSTGRES_PASSWORD: f1rhbtot9uj310md