name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install digitalocean doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Save DigitalOcean kubeconfig with short-lived credentials
      run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 sigo-tcc-k8s-cluster

    - name: Apply postgres config in k8s cluster
      run: kubectl apply -f ./postgres-config-secret.yml

    - name: Apply postgres deployment in k8s cluster
      run: kubectl apply -f ./postgres-deployment.yml

    - name: Apply ingress in k8s cluster
      run: kubectl apply -f ./ingress.yml
